# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "gorush"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  # gorush configuration via environment variables
  GORUSH_CORE_ENABLED = "true"
  GORUSH_CORE_ADDRESS = "0.0.0.0"
  GORUSH_CORE_PORT = "8080"
  GORUSH_ANDROID_ENABLED = "true"
  GORUSH_IOS_ENABLED = "false"
  GORUSH_HUAWEI_ENABLED = "false"
  GORUSH_STAT_ENGINE = "memory"
  GORUSH_LOG_LEVEL = "info"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthz"

[checks]
  [checks.api]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"